language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE veus;'

script:
  - phpunit

services:
  - mysql

notifications:
  email: false
