version: "2.1"
services:
  nginx:
    build: .docker/nginx
    command: nginx -g "daemon off;"
    links:
      - api
    ports:
      - "8000:80"
  migrate:
    build: .docker/php
    volumes:
     - .:/var/www/html/api
    working_dir: /var/www/html/api
    command: php artisan migrate 
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_KEY: oBtS3XWifM2GGkSe9abg
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: veus
      DB_USERNAME: root
      DB_PASSWORD: secret
  api:
    build: .docker/php
    volumes:
     - .:/var/www/html/api
    working_dir: /var/www/html/api/public
    command: php-fpm
    expose:
      - 9000
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: oBtS3XWifM2GGkSe9abg
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: veus
      DB_USERNAME: root
      DB_PASSWORD: secret
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=secret --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: veus
      MYSQL_USER: veus
      MYSQL_PASSWORD: secret