<?php

use App\Brand;
use App\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder {

    public function run()
    {
		$faker = Faker\Factory::create();

    	$products = [
			"Abaixador de língua (espátula de madeira), descartável, formato convencional liso, superfície e bordas perfeitamente acabadas, espessura e largura uniforme em toda sua extensão, medindo aproximadamente 14cm de comprimento, 1,4cm de largura x 0,5mm de espessura. Embalado em pacotes com 100 peças. Reembalado em caixa de papelão contendo 50 pacotes, constando os dados de identificação, nº lote, data de fabricação e procedência. Procedência Nacional.",
			"Adesivo hipoalergênico, para uso após punção venosa ou injeções. Caixa com 496 unidades.",
			"Agulha descartável 13x4,5, 26G, ½”, estéril, com ponta em formato de lança, parede ultrafina, código de cores transparentes do canhão que permite fácil checagem de refluxo e rápida identificação do calibre, cor do canhão bege. Embalada em caixa com 100 unidades. Procedência Nacional.",
			"Agulha descartável 25x7, 22GX, 1”, estéril, com ponta em formato de lança, parede ultrafina, código de cores transparentes do canhão que permite fácil checagem de refluxo e rápida identificação do calibre, cor do canhão preto. Embalada em caixa com 100 unidades.",
			"Álcool cetona, Frasco de 100ml.",
			"Álcool etílico 70%, desinfetante à base de álcool etílico a 70% P/V, indicado para superfícies fixas, anti-sepsia da pele em procedimentos de baixo e médio risco. Frasco plástico de 1 litro.",
			"Algodão Hidrófilo 500g, em camadas contínuas em forma de rolo (manta), provido de papel apropriado em toda sua extensão. O algodão deverá apresentar aspecto homogêneo e macio, boa absorvência, ausência de grumos ou quaisquer impurezas, ser inodoro, de cor branca (no mínimo 80% de brancura). Embalado em saco plástico individual. Procedência Nacional.",
			"Ampola de cloreto de potássio a 10%, com 10ml. Caixa com 200 ampolas. Caixa com 200 ampolas",
			"Ampola de cloreto de sódio a 20%, com 10ml. Caixa com 200 ampolas. Caixa com 200 ampolas",
			"Atadura crepe, medindo aproximadamente 12cm de largurax4,5m de comprimento, cor natural, com 13 fios, constituída de fios de algodão cru, bordas devidamente acabadas, elasticidade adequada, estar uniformemente enrolada e isenta de quaisquer defeitos, constando externamente os dados de identificação e procedência. Acondicionadas em pacote plástico contendo 12 unidades.",
			"Bandeja tamanho 30x20x4, confeccionada em aço inoxidável, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização.",
			"Braçadeira inox, estrutura em tubos de aço inox. Haste regulável em eixo maciço de aço inox. Concha em chapa curva de aço inox, com reclinagem de inclinação. Altura: máxima 1,07 m, mínima: 0,74 m",
			"Bobina de papel grau cirúrgico, com ou sem tinta indicativa para os seguintes processos de esterilização: vapor saturado, óxido de etileno, formaldeído, utilizado para o empacotamento de artigos médico-odonto-hospitalares e esterilização. Medida: 50x50. Procedência nacional",
			"Caixa de emergência, sem divisão, tamanho médio. Unidade Caixa cirúrgica perfurada, retangular, com tampa, medidas 20x10x5cm, confeccionada em aço inoxidável, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização. Embalagem contendo dados de identificação e procedência",
			"Carro para curativos, esmaltado, com tampo e prateleira esmaltada, tubos cromados, gradil do tampo revestido de borracha, rodas de 3\" de diâmetro, dimensões aproximadas 0,45x0,75x0,85m",
			"Cloridrato de lidocaína, geléia estéril 30g, uso profissional e/ou hospitalar. Caixa contendo 10 bisnagas de 30g + aplicador.Caixa contendo 10 bisnagas de 30g + aplicador",
			"Coletor de materiais perfurocortantes – caixa coletora para lixo contaminado de materialperfurocortante - com capacidade para 13 litros (útil 10 litros), confeccionada em papelãoondulado resistente à perfuração, com saco plástico e revestimento interno para descarte deobjetos, com alças externas, tampa de segurança com sistema de abertura e fechamentoprático e segurança ao manuseio, com instruções de uso e montagem impressasexternamente. Fabricado de acordo com a norma IPT NEA 55 e as normas ABNT NBR7500. Embaladas em caixa de papelão com 10 unidades, constando externamente os dadosde identificação, procedência e marca/fabricante. Procedência Nacional.Caixa com 10",
			"Compressa cirúrgica (campo operatório), sem radiopaco, medindo 45cmx50cm, constituídade quatro camadas de gaze sobrepostas, contendo aproximadamente 15 (8x7) fios por cm2em cada camada, cor branca, bordas devidamente acabadas em ponto overlok, formatoretangular, provida de alça, cantos arredondados. Peso aproximado: 40/41g. Pacote com 50unidades. Procedência Nacional.Pacote com 50",
			"Compressa de gaze hidrófila, confeccionada com 9 fios, tamanho nominal de 7,5x7,5, com08 dobras, área aproximada de 420cm 2 na compressa aberta, cor branca, bordasdevidamente voltadas para dentro, que evitem soltura de fios, isenta de quaisquer defeitosprejudiciais à sua perfeita utilização. Embalada em pacote plástico com 500 unidades,constando externamente os dados de identificação e procedência. Procedência Nacional. Pacote plástico com 500 und",
			"Compressa de gaze tipo queijo, confeccionada com 13 fios, tamanho normal de 91x91, com4 dobras, cor branca, bordas devidamente voltadas para dentro, que evitem soltura de fios,isenta de quaisquer defeitos prejudiciais à sua perfeita utilização. Embaladaindividualmente em pacote plástico, constando externamente os dados de identificação eprocedência. Procedência Nacional. Reembalada em caixa com 10 rolos.Rolo",
			"Detergente enzimático condicionado, com 3 enzimas, ideal para limpeza de equipamentos,instrumentos cirúrgicos e acessórios, não tóxico, não cáustico, não corrosivo, pH neutro,sem fosfato, biodegradável e desincrustante. Procedência Nacional. Frasco plástico de 1litro.Frasco plásticode 1 litro",
			"Escada, piso com revestimento plastilhado de borracha antiderrapante, com 05 degraus, emferro, pés com ponteiras de borracha",
			"Escadinha, piso com revestimento plastilhado de borracha antiderrapante, com 02 degrausem chapa de aço, pintura epóxi, pés com ponteiras de borracha, para auxílio ao paciente nasubida à mesa de atendimento clínico",
			"Escova ginecológica descartável, estéril, com cabo cilíndrico medindo 18cm decomprimento, facetado, medida da escova 2cm de comprimento, com cerdas em formatolevemente cônico, com a base mais larga que o ápice, disposta em 15 níveis paralelos dabase ao ápice. Embalagem plástica tipo “zip” com 10 unidades. Procedência nacional",
			"Esfignomanômetro adulto, tipo aneróide, capacidade de medida de 0 a 300mm/Hg, divisãode mostrador de 2mm/Hg, fecho de metal, braçadeira confeccionada em tecido antialérgico,sistema de válvula de ar com pêra e manguito feitos de borracha sintética, com certificado ede acordo com o Inmetro",
			"Esfignomanômetro pediátrico, tipo aneróide, capacidade de medida de 0 a 300mm/Hg,divisão de mostrador de 2mm/Hg, fecho de metal, braçadeira confeccionada em tecidoantialérgico, sistema de válvula de ar com pêra e manguito feitos de borracha sintética, comcertificado e de acordo com o Inmetro",
			"Estetoscópio com auscultador duplo de alta sensibilidade, capacitação precisa de mínimosruídos, olivas em borracha antialérgica macias, perfeita vedação contra sons do ambiente,armação metálica leve, resistente com ajuste automático de moda de aço, tubo em Y em açoinoxidável moldado sem solda, acondicionado em embalagem individual",
			"Fita autoclave 19mmx30m, para esterilização à vapor, aderência à variedade de pacotes,incluindo tecidos de algodão e papel, coloração bege sem listras antes da utilizaçãopassando a bege com listras negras bem identificáveis após a autoclavagem, papel crepe àbase de fibra de celulose, tinta termoreativa, estireno butadieno, resinas acrílicas e adesivo àbase de borracha natural e resina.Rolo de 30m",
			"Fita micropore, constituída de rayon viscoso não trançado, poroso, superfície adesivaimpregnada de substância à base de éter sintético quimicamente inerte, medindo25mmx10m, com capa, hipoalergênica, com corte uniforme bidirecional (para um curativode melhor aparência sem necessidade de uso de tesouras). Procedência nacional. Embaladaem caixa com 20 rolos com capa.Rolo de 25mmx10m com capa",
			"Fita micropore, constituída de rayon viscoso não trançado, poroso, superfície adesivaimpregnada de substância à base de éter sintético quimicamente inerte, medindo50mmx10m, hipoalergênica, com corte uniforme bidirecional (para um curativo de melhoraparência sem necessidade de uso de tesouras). Procedência nacional. Embalada em caixacom 20 rolos.Rolo de 50mmx10m",
			"Foco ginecológico sem espelho, luz intensa sem manchas, facho de luz altamente dirigido,corpo em metal com pintura eletrostática, altura ajustável, haste flexível cromada, lâmpadahalógena, alimentação bivolt 110 e 220 volts, base com 5 rodízios, proporcionando maiorestabilidade",
			"Fluxômetro, para oxigênio canalizado e/ou de cilindro, corpo de material resistente eantioxidante, visor composto de duas peças em material resistente, com escala graduada de0 a 15litros/mm O2, uma capa externa de proteção, flutuador esférico em aço inoxidável,sistema de compensação de pressão, roscas conforme norma, rosca de saída com dispositivopara adaptação de tubos de extensão, acompanha duas extensões de silicone transparente,atóxico, resistente a desinfecção por agentes químicos. Possuir: garantia, manual eassistência técnica",
			"Frasco para alimentação de 300ml. Unidade",
			"Furacim solução. Litro",
			"Gel condutivo para ultra-som (ECG), bisnaga contendo 100g. Embalagem contendo osdados de identificação, procedência, nº lote, data de fabricação e validade. ProcedênciaNacional. Frasco de 100g",
			"Histerômetro de collin, milimetrado, em aço inoxidável AISI 420, 28 cm, de acordo anorma NBR 7153-1. Tratamento integral e homogêneo no processo de fabricação, gravaçãode identificação do fabricante (legível, nome ou logomarca). Garantia de 10 anos, contradefeitos de fabricação. Registro na ANVISA e atender NBR 13402/ 13851/13852/13913 e13916",
			"Kit para nebulização, adulto, com conector de rosca. Unidade",
			"Kit para nebulização, pediátrico, com conector de rosca. UnidadeLanterna clínica, não elétrica, material aço inoxidável, quantidade pilhas 2, tamanho pilhaaaa ou aa, tipo foco fixo, comprimento 140, diâmetro 13, sem abaixador de língua",
			"Luva para procedimento tamanho P/M, em látex, com pó, não estéril, indicada paraprocedimentos não cirúrgicos, com a superfície do látex micro texturizada e acabamentoantiderrapante. Caixa com 100 unidades.Caixa com 100",
			"Luva plástica multiuso estéril, confeccionada em polietileno de alta densidade, transparente,espessura de 0,03 micras, apropriada para uso médico-hospitalar e para pequenostreinamentos hospitalares. Embalada individualmente, uma a uma, e reembalada em pacotescom 100 unidades. Procedência nacional. Pacote com 100 und",
			"Mesa auxiliar, esmaltada com rodízio estrutura em tubos redondos 19,05x1,20mm, tampo Unidadesuperior e inferior em chapa de aço 1,00mm, dimensões: 0,60m comprimento x 0,40mlargura x 0,80m altura.Mesa para exames clínicos, adulto, com dimensões de 1,80x0,60x0,80m, estrutura em tubosredondo com dimensões de 31,75x1,20mm, leito em espuma de alta densidade revestido emcourvin preto, encosto reclinável, com ponteiras de borracha nos pés",
			"Mesa ginecológica, estofada, estrutura em tubos redondos 31,75x1,20mm recurvados na corbranca, com espuma de alta densidade, revestido em courvim preto, assento fixo, encosto eapoio para pernas reclináveis com porta coxas e anexos cromados, pés com ponteiras,dimensões: 1,80x0,50x0,80cm",
			"Otoscópio clínico com fibra ótica, sem obstrução visual, sem obstrução de mecanismo esem reflexos de espéculo. Sistema de transmissão de luz por fibra ótica. Sistema fechadopara otoscopia pneumática. Lente de aumento grande e deslizante para fácil utilização.Quatro espéculos em polipropileno, tamanhos: 2mm, 3mm, 4mm e 5mm, esterilizáveis.Instrumento leve e resistente a impactos. Peso médio: 93 gramas, compatível para utilizaçãode 2 pilhas pequenas. Lâmpada reposição: 2440",
			"Pinça anatômica dissecção, serrilhada, 16cm, em aço inoxidável AISI 420, de finoacabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização, de acordo anorma NBR 7153-1. Tratamento integral e homogêneo no processo de fabricação, gravaçãode identificação do fabricante (legível, nome ou logomarca). Garantia de 10 anos, contradefeitos de fabricação. Registro na ANVISA e atender NBR 13402/ 13851/13852/13913 e13916",
			"Pinça Cheron, em aço inoxidável AISI 420, uterina, 25 cm, de fino acabamento, sem sinaisde oxidação, resistentes a desinfecção e esterilização, de acordo a norma NBR 7153-1.Tratamento integral e homogêneo no processo de fabricação, gravação de identificação dofabricante (legível, nome ou logomarca). Garantia de 10 anos, contra defeitos de fabricação.Registro na ANVISA e atender NBR 13402/ 13851/13852/13913 e 13916",
			"Pinça Halstead mosquito reta, com serrilha, em aço AISI 420, acabamento polido, semreentrâncias, com perfeito alinhamento e encaixe entre extremidades e travas, tamanho 12cm, de acordo a norma NBR 7153-1. Tratamento integral e homogêneo no processo defabricação, gravação de identificação do fabricante (legível, nome ou logomarca). Garantiade 10 anos, contra defeitos de fabricação. Registro na ANVISA e atender NBR 13402/13851/13852/13913 e 13916",
			"Pinça Kelly reta, em aço inoxidável AISI 400, comprimento de 16cm, de fino acabamento,sem sinais de oxidação, resistentes a desinfecção e esterilização, de acordo a norma NBR7153-1. Tratamento integral e homogêneo no processo de fabricação, gravação deidentificação do fabricante (legível, nome ou logomarca). Garantia de 10 anos, contradefeitos de fabricação. Registro na ANVISA e atender NBR 13402/ 13851/13852/13913 e 13916",
			"Pinça Kocher, am aço inox AISI 400, com forma curva, comprimento de 16cm, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização, de acordo a norma NBR 7153-1. Tratamento integral e homogêneo no processo de fabricação, gravação de identificação do fabricante (legível, nome ou logomarca). Garantia de 10 anos, contra defeitos de fabricação. Registro na ANVISA e atender NBR 13402/ 13851/13852/13913 e 13916",
			"Pinça de Pozzi, em aço inoxidável AISI 420, para utero, comprimento de 25cm, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização, de acordo a norma NBR 7153-1. Tratamento integral e homogêneo no processo de fabricação, gravação de identificação do fabricante (legível, nome ou logomarca). Garantia de 10 anos, contra defeitos de fabricação. Registro na ANVISA e atender NBR 13402/ 13851/13852/13913 e 13916",
			"Porta agulha Derf, em aço inox, com comprimento de 12cm. Unidade",
			"Porta agulha Mayo-Hegar, em aço inox, com comprimento de 14cm. Unidade",
			"Scalp nº 21, cateter para infusão venosa com agulha aguçada de bisel curto, trifacetado, com asas de plástico leve que se dobrem facilmente, tubo vinílico leve, flexível, transparente, atóxico e apirogênico, com conector rígido, leve e pequeno para conectar seringas, equipos ou qualquer outro dispositivo. Embalagem individual em saco plástico. Reembalado em pacote com 200 unidades. Procedência nacional. Pacote com 200 und",
			"Seringa descartável, confeccionada em plástico apropriado, uso único, com borracha noêmbolo para proteção, capacidade 10ml, bico comum, com agulha 25x7, esterilizada a gásóxido de etileno ou raio gama. Embalada individualmente em invólucro apropriado, capazde manter a sua integridade, contendo externamente os dados de identificação. Procedêncianacional. Reembalada em caixa com 100 unidadesde 10ml",
			"Seringa descartável, confeccionada em plástico apropriado, uso único, composta de trêspartes, com borracha no êmbolo para proteção, capacidade 20ml, bico slip, sem agulha,esterilizada a óxido de etileno ou raio gama. Embalada individualmente em invólucroapropriado, capaz de manter a sua integridade, contendo externamente os dados deidentificação, procedência, marca, tipo de esterilização, data de validade, nº do lote,responsável técnico e registro no Ministério da Saúde. Procedência nacional de 20ml",
			"Seringa de insulina descartável de 1ml, com agulha 13x0,45, confeccionada em polipropileno transparente, atóxica, com graduação externa, milimetrada, bico simples, tipo luer, com localização central, êmbolo com trava, pistão de borracha atóxica, siliconizada. Embalada individualmente em papel grau cirúrgico e filme termoplástico com abertura em pétala. Esterilização com validade de 05 (cinco) anos de 1ml",
			"Solução esterilizante após desinfetante à base de glutaraldeído, que atue sobre todos os tipos de microorganismos, indicado para desinfecção de artigos semi-críticos compatíveis quimicamente com aldeídos, tempo de contato aproximado de 30 minutos; esterilização de artigos críticos compatíveis quimicamente com aldeídos, tempo de contato de 10 horas; tempo entre ativação e vencimento da solução de 28 dias. Frasco plástico de 1 litro.",
			"Solução fisiológica – Cloreto de Sódio – 0,9%, estéril, indicada para assepsia de lentes de contato, inalações, limpeza de ferimentos, compressas, etc. Frasco plástico de 250ml, provido de bico dosador com tampinha estéril, embalado em saco transparente. Procedência nacional. Caixa com 24 frascos de 250ml. Caixa com 24 frascos de 250ml",
			"Solução ringer com lactato. Frasco de 100ml. Frasco de 100ml",
			"Sonda uretral nº 12, descartável, siliconizada, confeccionada em polivinil, atóxica, transparente, com dois orifícios central e lateral, esterilizada a raio gama cobalto 60. Embalada individualmente em filme polietileno, constando externamente os dados de identificação, procedência, data de fabricação e validade, nº do lote, calibre e registro no Ministério da Saúde. Reembalada em pacote com 10 unidades. Procedência nacional. Pacote com 10",
			"Suporte para soro, com altura fixa, base de ferro fundido, totalmente esmaltado, com 05 ganchos soldados verticalmente. Altura: 2,00m",
			"Tesoura Íris com duas pontas: fina e reta, 11cm, confeccionada em aço inoxidável, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização. Embalagem contendo dados de identificação e procedência",
			"Tesoura Íris, tipo ponta reta, 11,5cm, confeccionada em aço inoxidável, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização. Embalagem contendo dados de identificação e procedência",
			"Tesoura Metzembaum, longa, reta, 18cm, confeccionada em aço inoxidável, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização. Embalagem contendo dados de identificação e procedência",
			"Tesoura Spencer, para retirada de pontos, 13cm, confeccionada em aço inoxidável, de fino acabamento, sem sinais de oxidação, resistentes a desinfecção e esterilização. Embalagem contendo dados de identificação e procedência",
			"Tubo para coleta a vácuo, descartável, com EDTA, capacidade de 5ml, tampa roxa. Pacote Pacote com 50 com 50 unidades. unidades ",
			"Umidificador de O2 (oxigênio), plástico, frasco com capacidade de 250ml, com tampa e máscara",
			"Válvula de O2, com duas saídas, completa para aspiração de O2 (oxigênio). Unidade ",
			"Vaselina líquida (também conhecida como parafina líquida, óleo de vaselina, óleo de parafina e petrolato líquido). Aplicabilidade: adjuvante farmacotécnico. Frasco plástico de 1 litro. Frasco plástico de 1 litro"
		];

		foreach ($products as $product) {
			$produto = new Product;

			$produto->brand_id = Brand::inRandomOrder()
                ->first()->id;

			$length = FALSE != strpos($product, ',' ) ? strpos($product, ',' ) : (FALSE != strpos($product, '–' ) ? strpos($product, '–' ) : strlen($product));
			$produto->name = substr($product, 0, $length);
			$produto->price = $faker->randomNumber(2);
			$produto->quantity_stock = $faker->randomNumber(1);


			$produto->save();
				
		}
    }
}